name: student_project

channels:
- conda-forge

dependencies:
# - python=3.6
# - numpy
# - pandas
# # - jupyterlab
# - matplotlib
# - seaborn
# - scipy
# - statsmodels
- geopandas=0.8.0
# - libpysal
- pysal=2.0
