name: student_project

channel:
#- defaults
- conda-forge #geopandas says it can lead to issues to take packages from different channels

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
# Spatial analysis
- geopandas
- libpysal
- pip
- pip: