name: student_project

channels:
- conda-forge

dependencies:
# - python=3.6
- numpy=1.21.*
- pandas=1.3.*
- jupyter
- matplotlib=3.5.*
- seaborn=0.11.*
- scipy=1.7.*
- statsmodels=0.12.*
- geopandas=0.8.2
- libpysal=4.4.0
- pysal=2.4
